spring:
  application:
    name: itoken-eureka
  zipkin:
    base-url: http://47.114.63.61:9411
  boot:
    admin:
      client:
        url: http://47.114.63.61:8084

server:
  port: 8761

eureka:
  instance:
    hostname: 47.114.63.61
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://47.114.63.61:8761/eureka/,http://47.114.63.61:8861/eureka/,http://47.114.63.61:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # 注意：此处在视频里是 include: ["health", "info"] 但已无效了，请修改
        include: health,info