spring:
  application:
    name: itoken-zipkin
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 9411

management:
  metrics:
    web:
      server:
        auto-time-requests: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/